//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILG.Codex.CodexR4.CodexSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class SQLConnectionStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQLConnectionStrings defaultInstance = ((SQLConnectionStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQLConnectionStrings())));
        
        public static SQLConnectionStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsConnectionString {
            get {
                return ((bool)(this["IsConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString_CodexDS {
            get {
                return ((string)(this["ConnectionString_CodexDS"]));
            }
            set {
                this["ConnectionString_CodexDS"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_CodexDS_ConnectionString {
            get {
                return ((string)(this["App_CodexDS_ConnectionString"]));
            }
        }
    }
}
